package com.api.finance.core.utils.enums;

import lombok.Getter;

@Getter
public enum Country {

    AFGHANISTAN("Afghanistan", "AF"),
    ALBANIA("Albania", "AL"),
    ALGERIA("Algeria", "DZ"),
    ANDORRA("Andorra", "AD"),
    ANGOLA("Angola", "AO"),
    ANTIGUA_DEPS("Antigua & Deps", "AG"),
    ARGENTINA("Argentina", "AR"),
    ARMENIA("Armenia", "AM"),
    AUSTRALIA("Australia", "AU"),
    AUSTRIA("Austria", "AT"),
    AZERBAIJAN("Azerbaijan", "AZ"),
    BAHAMAS("Bahamas", "BS"),
    BAHRAIN("Bahrain", "BH"),
    BANGLADESH("Bangladesh", "BD"),
    BARBADOS("Barbados", "BB"),
    BELARUS("Belarus", "BY"),
    BELGIUM("Belgium", "BE"),
    BELIZE("Belize", "BZ"),
    BENIN("Benin", "BJ"),
    BHUTAN("Bhutan", "BT"),
    BOLIVIA("Bolivia", "BO"),
    BOSNIA_HERZEGOVINA("Bosnia Herzegovina", "BA"),
    BOTSWANA("Botswana", "BW"),
    BRAZIL("Brazil", "BR"),
    BRUNEI("Brunei", "BN"),
    BULGARIA("Bulgaria", "BG"),
    BURKINA("Burkina", "BF"),
    BURMA("Burma", "MM"),
    BURUNDI("Burundi", "BI"),
    CAMBODIA("Cambodia", "KH"),
    CAMEROON("Cameroon", "CM"),
    CANADA("Canada", "CA"),
    CAPE_VERDE("Cape Verde", "CV"),
    CENTRAL_AFRICAN_REP("Central African Rep", "CF"),
    CHAD("Chad", "TD"),
    CHILE("Chile", "CL"),
    CHINA("People's Republic of China", "CN"),
    TAIWAN("Republic of China", "TW"),
    COLOMBIA("Colombia", "CO"),
    COMOROS("Comoros", "KM"),
    DEMOCRATIC_REPUBLIC_OF_THE_CONGO("Democratic Republic of the Congo", "CD"),
    REPUBLIC_OF_THE_CONGO("Republic of the Congo", "CG"),
    COSTA_RICA("Costa Rica", "CR"),
    CROATIA("Croatia", "HR"),
    CUBA("Cuba", "CU"),
    CYPRUS("Cyprus", "CY"),
    CZECH_REPUBLIC("Czech Republic", "CZ"),
    DENMARK("Denmark", "DK"),
    DJIBOUTI("Djibouti", "DJ"),
    DOMINICA("Dominica", "DM"),
    DOMINICAN_REPUBLIC("Dominican Republic", "DO"),
    EAST_TIMOR("East Timor", "TL"),
    ECUADOR("Ecuador", "EC"),
    EGYPT("Egypt", "EG"),
    EL_SALVADOR("El Salvador", "SV"),
    EQUATORIAL_GUINEA("Equatorial Guinea", "GQ"),
    ERITREA("Eritrea", "ER"),
    ESTONIA("Estonia", "EE"),
    ETHIOPIA("Ethiopia", "ET"),
    FIJI("Fiji", "FJ"),
    FINLAND("Finland", "FI"),
    FRANCE("France", "FR"),
    GABON("Gabon", "GA"),
    GAZA_STRIP("Gaza Strip", "PS"), // Faixa de Gaza
    THE_GAMBIA("The Gambia", "GM"),
    GEORGIA("Georgia", "GE"),
    GERMANY("Germany", "DE"),
    GHANA("Ghana", "GH"),
    GREECE("Greece", "GR"),
    GRENADA("Grenada", "GD"),
    GUATEMALA("Guatemala", "GT"),
    GUINEA("Guinea", "GN"),
    GUINEA_BISSAU("Guinea-Bissau", "GW"),
    GUYANA("Guyana", "GY"),
    HAITI("Haiti", "HT"),
    HONDURAS("Honduras", "HN"),
    HUNGARY("Hungary", "HU"),
    ICELAND("Iceland", "IS"),
    INDIA("India", "IN"),
    INDONESIA("Indonesia", "ID"),
    IRAN("Iran", "IR"),
    IRAQ("Iraq", "IQ"),
    REPUBLIC_OF_IRELAND("Republic of Ireland", "IE"),
    ISRAEL("Israel", "IL"),
    ITALY("Italy", "IT"),
    IVORY_COAST("Ivory Coast", "CI"),
    JAMAICA("Jamaica", "JM"),
    JAPAN("Japan", "JP"),
    JORDAN("Jordan", "JO"),
    KAZAKHSTAN("Kazakhstan", "KZ"),
    KENYA("Kenya", "KE"),
    KIRIBATI("Kiribati", "KI"),
    NORTH_KOREA("North Korea", "KP"),
    SOUTH_KOREA("South Korea", "KR"),
    KOSOVO("Kosovo", "XK"), // Código não oficial
    KUWAIT("Kuwait", "KW"),
    KYRGYZSTAN("Kyrgyzstan", "KG"),
    LAOS("Laos", "LA"),
    LATVIA("Latvia", "LV"),
    LEBANON("Lebanon", "LB"),
    LESOTHO("Lesotho", "LS"),
    LIBERIA("Liberia", "LR"),
    LIBYA("Libya", "LY"),
    LIECHTENSTEIN("Liechtenstein", "LI"),
    LITHUANIA("Lithuania", "LT"),
    LUXEMBOURG("Luxembourg", "LU"),
    MACEDONIA("Macedonia", "MK"),
    MADAGASCAR("Madagascar", "MG"),
    MALAWI("Malawi", "MW"),
    MALAYSIA("Malaysia", "MY"),
    MALDIVES("Maldives", "MV"),
    MALI("Mali", "ML"),
    MALTA("Malta", "MT"),
    MARSHALL_ISLANDS("Marshall Islands", "MH"),
    MAURITANIA("Mauritania", "MR"),
    MAURITIUS("Mauritius", "MU"),
    MEXICO("Mexico", "MX"),
    MICRONESIA("Micronesia", "FM"),
    MOLDOVA("Moldova", "MD"),
    MONACO("Monaco", "MC"),
    MONGOLIA("Mongolia", "MN"),
    MONTENEGRO("Montenegro", "ME"),
    MOROCCO("Morocco", "MA"),
    MOZAMBIQUE("Mozambique", "MZ"),
    NAMIBIA("Namibia", "NA"),
    NAURU("Nauru", "NR"),
    NEPAL("Nepal", "NP"),
    NETHERLANDS("Netherlands", "NL"),
    NEW_ZEALAND("New Zealand", "NZ"),
    NICARAGUA("Nicaragua", "NI"),
    NIGER("Niger", "NE"),
    NIGERIA("Nigeria", "NG"),
    NORWAY("Norway", "NO"),
    OMAN("Oman", "OM"),
    PAKISTAN("Pakistan", "PK"),
    PALAU("Palau", "PW"),
    PANAMA("Panama", "PA"),
    PAPUA_NEW_GUINEA("Papua New Guinea", "PG"),
    PARAGUAY("Paraguay", "PY"),
    PERU("Peru", "PE"),
    PHILIPPINES("Philippines", "PH"),
    POLAND("Poland", "PL"),
    PORTUGAL("Portugal", "PT"),
    QATAR("Qatar", "QA"),
    ROMANIA("Romania", "RO"),
    RUSSIAN_FEDERATION("Russian Federation", "RU"),
    RWANDA("Rwanda", "RW"),
    GRENADINES("Grenadines", "VC"), // São vicente e Granadinas
    SAMOA("Samoa", "WS"),
    SAN_MARINO("San Marino", "SM"),
    SAO_TOME_PRINCIPE("Sao Tome & Principe", "ST"),
    SAUDI_ARABIA("Saudi Arabia", "SA"),
    SENEGAL("Senegal", "SN"),
    SERBIA("Serbia", "RS"),
    SEYCHELLES("Seychelles", "SC"),
    SIERRA_LEONE("Sierra Leone", "SL"),
    SINGAPORE("Singapore", "SG"),
    SLOVAKIA("Slovakia", "SK"),
    SLOVENIA("Slovenia", "SI"),
    SOLOMON_ISLANDS("Solomon Islands", "SB"),
    SOMALIA("Somalia", "SO"),
    SOUTH_AFRICA("South Africa", "ZA"),
    SPAIN("Spain", "ES"),
    SRI_LANKA("Sri Lanka", "LK"),
    SUDAN("Sudan", "SD"),
    SURINAME("Suriname", "SR"),
    SWAZILAND("Swaziland", "SZ"),
    SWEDEN("Sweden", "SE"),
    SWITZERLAND("Switzerland", "CH"),
    SYRIA("Syria", "SY"),
    TAJIKISTAN("Tajikistan", "TJ"),
    TANZANIA("Tanzania", "TZ"),
    THAILAND("Thailand", "TH"),
    TOGO("Togo", "TG"),
    TONGA("Tonga", "TO"),
    TRINIDAD_TOBAGO("Trinidad & Tobago", "TT"),
    TUNISIA("Tunisia", "TN"),
    TURKEY("Turkey", "TR"),
    TURKMENISTAN("Turkmenistan", "TM"),
    TUVALU("Tuvalu", "TV"),
    UGANDA("Uganda", "UG"),
    UKRAINE("Ukraine", "UA"),
    UNITED_ARAB_EMIRATES("United Arab Emirates", "AE"),
    UNITED_KINGDOM("United Kingdom", "GB"),
    USA("United States of America", "US"),
    URUGUAY("Uruguay", "UY"),
    UZBEKISTAN("Uzbekistan", "UZ"),
    VANUATU("Vanuatu", "VU"),
    VATICAN_CITY("Vatican City", "VA"),
    VENEZUELA("Venezuela", "VE"),
    VIETNAM("Vietnam", "VN"),
    YEMEN("Yemen", "YE"),
    ZAMBIA("Zambia", "ZM"),
    ZIMBABWE("Zimbabwe", "ZW");

    private final String country;

    private final String code;

    Country(String country, String code) {
        this.country = country;
        this.code = code;
    }

}
